[theme]
primaryColor = "#0070d2"
backgroundColor = "#f4f6f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#181818"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = false